# Generated by Django 5.2.4 on 2025-07-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tulgan_kun',
            field=models.DateField(blank=True, null=True),
        ),
    ]
